#ifndef TEA_TOKEN_H
#define TEA_TOKEN_H

typedef enum
{
    // Single-character tokens.
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
    TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET,
    TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
    TOKEN_COMMA, TOKEN_DOT,
    TOKEN_COLON, TOKEN_QUESTION, /*TOKEN_SEMICOLON,*/
    TOKEN_MINUS, TOKEN_PLUS,
    TOKEN_SLASH, TOKEN_STAR,

    // One or two character tokens.
    TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS,
    TOKEN_PLUS_EQUAL, TOKEN_MINUS_EQUAL, TOKEN_STAR_EQUAL, TOKEN_SLASH_EQUAL,
    TOKEN_BANG, TOKEN_BANG_EQUAL,
    TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
    TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_LESS, TOKEN_LESS_EQUAL,
    TOKEN_PERCENT, TOKEN_PERCENT_EQUAL,
    TOKEN_DOT_DOT, TOKEN_DOT_DOT_DOT,

    // Literals.
    TOKEN_NAME, TOKEN_STRING, TOKEN_NUMBER,

    // Keywords.
    TOKEN_AND, TOKEN_CLASS, TOKEN_ELSE, TOKEN_FALSE,
    TOKEN_FOR, TOKEN_FUNCTION, TOKEN_CASE, TOKEN_SWITCH, TOKEN_DEFAULT,
    TOKEN_IF, TOKEN_NULL, TOKEN_OR,
    TOKEN_IMPORT, TOKEN_FROM,
    TOKEN_RETURN, TOKEN_SUPER, TOKEN_THIS,
    TOKEN_CONTINUE, TOKEN_BREAK,
    TOKEN_TRUE, TOKEN_VAR, TOKEN_WHILE,

    //TOKEN_LINE,

    TOKEN_ERROR, TOKEN_EOF
} TeaTokenType;

typedef struct
{
    TeaTokenType type;
    const char* start;
    int length;
    int line;
} TeaToken;

#endif