tea_api.o: tea_api.c tea.h teaconf.h tea_state.h tea_def.h tea_parse.h \
 tea_obj.h tea_lex.h tea_buf.h tea_gc.h tea_str.h tea_func.h tea_map.h \
 tea_vm.h tea_err.h tea_errmsg.h tea_tab.h
tea_bc.o: tea_bc.c tea_bc.h tea_def.h
tea_bcread.o: tea_bcread.c tea_def.h tea_bcdump.h tea.h teaconf.h \
 tea_state.h tea_parse.h tea_obj.h tea_lex.h tea_buf.h tea_gc.h tea_str.h \
 tea_err.h tea_errmsg.h tea_func.h tea_vm.h
tea_bcwrite.o: tea_bcwrite.c tea_bcdump.h tea.h teaconf.h tea_state.h \
 tea_def.h tea_parse.h tea_obj.h tea_lex.h tea_buf.h tea_gc.h tea_str.h \
 tea_vm.h tea_err.h tea_errmsg.h
tea_buf.o: tea_buf.c tea_buf.h tea_def.h tea_gc.h tea_state.h tea.h \
 teaconf.h tea_parse.h tea_obj.h tea_lex.h tea_str.h
tea_debug.o: tea_debug.c tea_debug.h tea_obj.h tea.h teaconf.h tea_def.h \
 tea_state.h tea_parse.h tea_lex.h tea_buf.h tea_gc.h tea_str.h \
 tea_func.h tea_bc.h
tea_err.o: tea_err.c tea_def.h tea_err.h tea_state.h tea.h teaconf.h \
 tea_parse.h tea_obj.h tea_lex.h tea_buf.h tea_gc.h tea_str.h \
 tea_errmsg.h tea_vm.h tea_func.h tea_bcdump.h
tea_func.o: tea_func.c tea_state.h tea.h teaconf.h tea_def.h tea_parse.h \
 tea_obj.h tea_lex.h tea_buf.h tea_gc.h tea_str.h tea_vm.h tea_err.h \
 tea_errmsg.h
tea_gc.o: tea_gc.c tea_state.h tea.h teaconf.h tea_def.h tea_parse.h \
 tea_obj.h tea_lex.h tea_buf.h tea_gc.h tea_str.h tea_tab.h
tea_import.o: tea_import.c tea.h teaconf.h tealib.h tea_arch.h \
 tea_state.h tea_def.h tea_parse.h tea_obj.h tea_lex.h tea_buf.h tea_gc.h \
 tea_str.h tea_vm.h tea_err.h tea_errmsg.h tea_import.h tea_loadlib.h \
 tea_tab.h
tea_lex.o: tea_lex.c tea_def.h tea_char.h tea_obj.h tea.h teaconf.h \
 tea_lex.h tea_buf.h tea_gc.h tea_state.h tea_parse.h tea_str.h tea_utf.h \
 tea_err.h tea_errmsg.h
tea_load.o: tea_load.c tea.h teaconf.h tea_buf.h tea_def.h tea_gc.h \
 tea_state.h tea_parse.h tea_obj.h tea_lex.h tea_str.h tea_import.h \
 tea_err.h tea_errmsg.h tea_vm.h tea_bcdump.h
tea_loadlib.o: tea_loadlib.c tea.h teaconf.h tea_def.h tea_arch.h
tea_map.o: tea_map.c tea_map.h tea_obj.h tea.h teaconf.h tea_def.h \
 tea_gc.h tea_state.h tea_parse.h tea_lex.h tea_buf.h tea_str.h
tea_obj.o: tea_obj.c tea_def.h tea_gc.h tea_state.h tea.h teaconf.h \
 tea_parse.h tea_obj.h tea_lex.h tea_buf.h tea_str.h tea_map.h tea_tab.h \
 tea_vm.h tea_err.h tea_errmsg.h
tea_parse.o: tea_parse.c tea_def.h tea_state.h tea.h teaconf.h \
 tea_parse.h tea_obj.h tea_lex.h tea_buf.h tea_gc.h tea_str.h tea_func.h \
 tea_vm.h tea_err.h tea_errmsg.h tea_bc.h tea_tab.h
tea_state.o: tea_state.c tealib.h tea.h teaconf.h tea_def.h tea_state.h \
 tea_parse.h tea_obj.h tea_lex.h tea_buf.h tea_gc.h tea_str.h tea_vm.h \
 tea_err.h tea_errmsg.h tea_import.h tea_tab.h
tea_str.o: tea_str.c tea_str.h tea_def.h tea_obj.h tea.h teaconf.h \
 tea_state.h tea_parse.h tea_lex.h tea_buf.h tea_gc.h tea_vm.h tea_err.h \
 tea_errmsg.h tea_tab.h
tea_tab.o: tea_tab.c tea_gc.h tea_state.h tea.h teaconf.h tea_def.h \
 tea_parse.h tea_obj.h tea_lex.h tea_buf.h tea_str.h tea_tab.h
tea_utf.o: tea_utf.c tea_def.h tea_utf.h tea_obj.h tea.h teaconf.h \
 tea_str.h tea_gc.h tea_state.h tea_parse.h tea_lex.h tea_buf.h
tea_vm.o: tea_vm.c tea_def.h tea_obj.h tea.h teaconf.h tea_func.h \
 tea_map.h tea_str.h tea_gc.h tea_state.h tea_parse.h tea_lex.h tea_buf.h \
 tea_vm.h tea_err.h tea_errmsg.h tea_utf.h tea_import.h tea_bc.h \
 tea_tab.h
