tea_api.o: tea_api.c tea.h teaconf.h tea_state.h tea_def.h tea_value.h \
 tea_array.h tea_object.h tea_memory.h tea_chunk.h tea_opcodes.h \
 tea_table.h tea_string.h tea_func.h tea_map.h tea_vm.h tea_do.h
tea_chunk.o: tea_chunk.c tea_chunk.h tea_def.h tea_value.h tea_array.h \
 tea_opcodes.h tea_memory.h tea_state.h tea.h teaconf.h tea_object.h \
 tea_table.h tea_vm.h
tea_compiler.o: tea_compiler.c tea_def.h tea_state.h tea.h teaconf.h \
 tea_value.h tea_array.h tea_object.h tea_memory.h tea_chunk.h \
 tea_opcodes.h tea_table.h tea_compiler.h tea_scanner.h tea_token.h \
 tea_func.h tea_string.h tea_gc.h tea_import.h tea_do.h
tea_core.o: tea_core.c tea.h teaconf.h tea_vm.h tea_state.h tea_def.h \
 tea_value.h tea_array.h tea_object.h tea_memory.h tea_chunk.h \
 tea_opcodes.h tea_table.h tea_string.h tea_core.h tea_utf.h
tea_debug.o: tea_debug.c tea_debug.h tea_chunk.h tea_def.h tea_value.h \
 tea_array.h tea_opcodes.h tea_object.h tea.h teaconf.h tea_memory.h \
 tea_table.h tea_state.h
tea_do.o: tea_do.c tea_def.h tea_do.h tea_state.h tea.h teaconf.h \
 tea_value.h tea_array.h tea_object.h tea_memory.h tea_chunk.h \
 tea_opcodes.h tea_table.h tea_func.h tea_vm.h tea_compiler.h \
 tea_scanner.h tea_token.h tea_debug.h
tea_fileclass.o: tea_fileclass.c tea.h teaconf.h tea_vm.h tea_state.h \
 tea_def.h tea_value.h tea_array.h tea_object.h tea_memory.h tea_chunk.h \
 tea_opcodes.h tea_table.h tea_string.h tea_core.h
tea_func.o: tea_func.c tea_state.h tea.h teaconf.h tea_def.h tea_value.h \
 tea_array.h tea_object.h tea_memory.h tea_chunk.h tea_opcodes.h \
 tea_table.h tea_vm.h
tea_gc.o: tea_gc.c tea_state.h tea.h teaconf.h tea_def.h tea_value.h \
 tea_array.h tea_object.h tea_memory.h tea_chunk.h tea_opcodes.h \
 tea_table.h tea_gc.h tea_compiler.h tea_scanner.h tea_token.h
tea_import.o: tea_import.c tea.h teaconf.h tealib.h tea_state.h tea_def.h \
 tea_value.h tea_array.h tea_object.h tea_memory.h tea_chunk.h \
 tea_opcodes.h tea_table.h tea_import.h tea_util.h tea_vm.h tea_string.h \
 tea_do.h tea_loadlib.h
tea_iolib.o: tea_iolib.c tea.h teaconf.h tealib.h tea_string.h \
 tea_object.h tea_def.h tea_memory.h tea_value.h tea_array.h tea_chunk.h \
 tea_opcodes.h tea_table.h tea_import.h tea_state.h tea_core.h tea_vm.h
tea_listclass.o: tea_listclass.c tea.h teaconf.h tea_vm.h tea_state.h \
 tea_def.h tea_value.h tea_array.h tea_object.h tea_memory.h tea_chunk.h \
 tea_opcodes.h tea_table.h tea_core.h tea_string.h
tea_loadlib.o: tea_loadlib.c tea.h teaconf.h
tea_map.o: tea_map.c tea_map.h tea_object.h tea.h teaconf.h tea_def.h \
 tea_memory.h tea_value.h tea_array.h tea_chunk.h tea_opcodes.h \
 tea_table.h
tea_mapclass.o: tea_mapclass.c tea_vm.h tea_state.h tea.h teaconf.h \
 tea_def.h tea_value.h tea_array.h tea_object.h tea_memory.h tea_chunk.h \
 tea_opcodes.h tea_table.h tea_core.h tea_map.h
tea_mathlib.o: tea_mathlib.c tea.h teaconf.h tealib.h tea_import.h \
 tea_state.h tea_def.h tea_value.h tea_array.h tea_object.h tea_memory.h \
 tea_chunk.h tea_opcodes.h tea_table.h tea_core.h
tea_memory.o: tea_memory.c tea.h teaconf.h tea_def.h tea_memory.h \
 tea_value.h tea_array.h tea_state.h tea_object.h tea_chunk.h \
 tea_opcodes.h tea_table.h
tea_object.o: tea_object.c tea_memory.h tea_value.h tea_def.h tea_array.h \
 tea_object.h tea.h teaconf.h tea_chunk.h tea_opcodes.h tea_table.h \
 tea_map.h tea_string.h tea_state.h tea_vm.h
tea_oslib.o: tea_oslib.c tea.h teaconf.h tealib.h tea_import.h \
 tea_state.h tea_def.h tea_value.h tea_array.h tea_object.h tea_memory.h \
 tea_chunk.h tea_opcodes.h tea_table.h tea_core.h
tea_randomlib.o: tea_randomlib.c tea.h teaconf.h tealib.h tea_import.h \
 tea_state.h tea_def.h tea_value.h tea_array.h tea_object.h tea_memory.h \
 tea_chunk.h tea_opcodes.h tea_table.h tea_core.h
tea_rangeclass.o: tea_rangeclass.c tea.h teaconf.h tea_vm.h tea_state.h \
 tea_def.h tea_value.h tea_array.h tea_object.h tea_memory.h tea_chunk.h \
 tea_opcodes.h tea_table.h tea_core.h
tea_scanner.o: tea_scanner.c tea_def.h tea_value.h tea_array.h \
 tea_scanner.h tea_state.h tea.h teaconf.h tea_object.h tea_memory.h \
 tea_chunk.h tea_opcodes.h tea_table.h tea_token.h tea_string.h tea_utf.h
tea_state.o: tea_state.c tea_state.h tea.h teaconf.h tea_def.h \
 tea_value.h tea_array.h tea_object.h tea_memory.h tea_chunk.h \
 tea_opcodes.h tea_table.h tea_core.h tea_vm.h tea_string.h tea_util.h \
 tea_do.h tea_gc.h
tea_string.o: tea_string.c tea_string.h tea_object.h tea.h teaconf.h \
 tea_def.h tea_memory.h tea_value.h tea_array.h tea_chunk.h tea_opcodes.h \
 tea_table.h tea_state.h tea_vm.h
tea_stringclass.o: tea_stringclass.c tea.h teaconf.h tea_vm.h tea_state.h \
 tea_def.h tea_value.h tea_array.h tea_object.h tea_memory.h tea_chunk.h \
 tea_opcodes.h tea_table.h tea_core.h tea_utf.h tea_string.h
tea_syslib.o: tea_syslib.c tea.h teaconf.h tealib.h tea_import.h \
 tea_state.h tea_def.h tea_value.h tea_array.h tea_object.h tea_memory.h \
 tea_chunk.h tea_opcodes.h tea_table.h tea_core.h
tea_table.o: tea_table.c tea_gc.h tea_state.h tea.h teaconf.h tea_def.h \
 tea_value.h tea_array.h tea_object.h tea_memory.h tea_chunk.h \
 tea_opcodes.h tea_table.h
tea_timelib.o: tea_timelib.c tea.h teaconf.h tealib.h tea_import.h \
 tea_state.h tea_def.h tea_value.h tea_array.h tea_object.h tea_memory.h \
 tea_chunk.h tea_opcodes.h tea_table.h tea_core.h
tea_utf.o: tea_utf.c tea_utf.h tea_def.h tea_value.h tea_array.h \
 tea_object.h tea.h teaconf.h tea_memory.h tea_chunk.h tea_opcodes.h \
 tea_table.h tea_string.h
tea_util.o: tea_util.c tea_util.h tea_vm.h tea_state.h tea.h teaconf.h \
 tea_def.h tea_value.h tea_array.h tea_object.h tea_memory.h tea_chunk.h \
 tea_opcodes.h tea_table.h tea_string.h
tea_value.o: tea_value.c tea_object.h tea.h teaconf.h tea_def.h \
 tea_memory.h tea_value.h tea_array.h tea_chunk.h tea_opcodes.h \
 tea_table.h tea_string.h
tea_vm.o: tea_vm.c tea_def.h tea_compiler.h tea_scanner.h tea_state.h \
 tea.h teaconf.h tea_value.h tea_array.h tea_object.h tea_memory.h \
 tea_chunk.h tea_opcodes.h tea_table.h tea_token.h tea_debug.h tea_func.h \
 tea_map.h tea_string.h tea_vm.h tea_utf.h tea_import.h tea_do.h
