/*
** tea_errmsg.h
** VM error messages
*/

ERRDEF(MEM, "Not enough memory")

ERRDEF(TOSTR, "'tostring' must return a string")
ERRDEF(STKOV, "Stack overflow")
ERRDEF(CSTKOV, "C stack overflow")
ERRDEF(CALL, "'%s' is not callable")

ERRDEF(NOARGS, "Expected 0 arguments but got %d")
ERRDEF(ARGS, "Expected %d arguments, but got %d")
ERRDEF(NOVAL, "Expected value")

ERRDEF(PATH, "Unable to resolve path '%s'")
ERRDEF(NOMOD, "Unknown module '%s'")
ERRDEF(NOPATH, "Could not resolve path '%s'")
ERRDEF(READPATH, "Could not read '%s'")

/* VM errors */
ERRDEF(METH, "Undefined method '%s'")
ERRDEF(OBJMETH, "Only objects have methods, '%s' given")
ERRDEF(MODVAR, "Undefined variable '%s' in '%s' module")
ERRDEF(NOSTATIC, "'%s' is not static. Only static methods can be invoked directly from a class")
ERRDEF(NOMETH, "'%s' has no method '%s'")
ERRDEF(NUMSLICE, "Slice index must be a number")
ERRDEF(SLICE, "'%s' is not sliceable")
ERRDEF(SUBSCR, "'%s' is not subscriptable")
ERRDEF(INSTSUBSCR, "'%s' instance is not subscriptable")
ERRDEF(NUMRANGE, "Range index must be a number")
ERRDEF(IDXRANGE, "Range index out of bounds")
ERRDEF(NUMLIST, "List index must be a number")
ERRDEF(IDXLIST, "List index out of bounds")
ERRDEF(HASH, "Map key isn't hashable")
ERRDEF(KHASH, "'%s' isn't a hashable map key")
ERRDEF(MAPKEY, "Key does not exist within map")
ERRDEF(NUMSTR, "String index must be a number, got '%s'")
ERRDEF(IDXSTR, "String index out of bounds")
ERRDEF(SETSUBSCR, "'%s' does not support item assignment")
ERRDEF(OBJATTR, "Only objects have properties")
ERRDEF(INSTATTR, "'%s' instance has no property: '%s'")
ERRDEF(CLSATTR, "'%s' class has no property: '%s'")
ERRDEF(MODATTR, "'%s' module has no property: '%s'")
ERRDEF(MAPATTR, "Map has no property: '%s'")
ERRDEF(NOATTR, "'%s' has no property '%s'")
ERRDEF(SETATTR, "Cannot set property on type '%s'")
ERRDEF(UNOP, "Attempt to use '%s' unary operator with '%s'")
ERRDEF(BIOP, "Attempt to use '%s' operator with '%s' and '%s'")
ERRDEF(VAR, "Undefined variable '%s'")
ERRDEF(RANGE, "Range operands must be numbers")
ERRDEF(UNPACK, "Can only unpack lists")
ERRDEF(MAXUNPACK, "Too many values to unpack")
ERRDEF(MINUNPACK, "Not enough values to unpack")
ERRDEF(SUPER, "Superclass must be a class")
ERRDEF(IS, "Right operand must be a class")
ERRDEF(ITER, "'%s' is not iterable")
ERRDEF(BUILTINSELF, "Cannot inherit from built-in '%s'")
ERRDEF(SELF, "A class can't inherit from itself")
ERRDEF(EXTMETH, "Cannot assign extension method to '%s'")
ERRDEF(VARMOD, "'%s' variable can't be found in module '%s'")

ERRDEF(ASSERT, "Assertion failed")
ERRDEF(OPEN, "Unable to open file '%s'")
ERRDEF(DUMP, "Unable to dump given function")
ERRDEF(STRFMT, "Invalid option '%s' to 'format'")

/* Lexer/parser errors */
ERRDEF(XNUMBER, "Malformed number")
ERRDEF(XUND, "Cannot have consecutive '_' in number literal")
ERRDEF(XLUND, "Cannot have leading '_' in number literal")
ERRDEF(XHEX, "Invalid hex number")
ERRDEF(XSCI, "Unterminated scientific notation")
ERRDEF(XSFMT, "String interpolation too deep")
ERRDEF(XSTR, "Unterminated string")
ERRDEF(XHESC, "Incomplete hex escape sequence")
ERRDEF(XUESC, "Incomplete unicode escape sequence")
ERRDEF(XESC, "Invalid escape character")
ERRDEF(XLCOM, "Unterminated block comment")
ERRDEF(XCHAR, "Unexpected character")
ERRDEF(XLOOP, "Loop body too big")
ERRDEF(XKCONST, "Too many constants in one chunk")
ERRDEF(XJUMP, "Too much code to jump over")
ERRDEF(XUPVAL, "Too many closure variables in function")
ERRDEF(XLOCALS, "Too many local variables in function")
ERRDEF(XARGS, "Can't have more than 255 arguments")
ERRDEF(XVCONST, "Cannot assign to a const variable")
ERRDEF(XSUPERO, "Can't use 'super' outside of a class")
ERRDEF(XSUPERK, "Can't use 'super' in a class with no superclass")
ERRDEF(XTHISO, "Can't use 'this' outside of a class")
ERRDEF(XTHISM, "Can't use 'this' inside a static method")
ERRDEF(XSTATIC, "Can't use 'static' outside of a class")
ERRDEF(XASSIGN, "Invalid assignment target")
ERRDEF(XEXPR, "Expected expression")
ERRDEF(XDUPARGS, "Duplicate parameter name in function declaration")
ERRDEF(XSPREADARGS, "Spread parameter must be last in the parameter list")
ERRDEF(XSPREADOPT, "Spread parameter cannot have an optional value")
ERRDEF(XOPT, "Cannot have non-optional parameter after optional")
ERRDEF(XMAXARGS, "Cannot have more than 255 parameters")
ERRDEF(XMETH, "Invalid method name")
ERRDEF(XSINGLEREST, "Cannot rest single variable")
ERRDEF(XVALASSIGN, "Not enough values to assign to")
ERRDEF(XBREAK, "Cannot use 'break' outside of a loop")
ERRDEF(XCONTINUE, "Cannot use 'continue' outside of a loop")
ERRDEF(XCASE, "Unexpected case after default")
ERRDEF(XRET, "Can't return from top-level code")
ERRDEF(XINIT, "Can't return a value from a constructor")
ERRDEF(XTOKEN, "Expected '%s'")
ERRDEF(XDOTS, "Multiple '...'")
ERRDEF(XSWITCH, "Switch statement can not have more than 256 case blocks")
ERRDEF(XVARS, "Cannot have more than 255 variables")
ERRDEF(XVASSIGN, "Not enough values to assign to")

#undef ERRDEF